export const metadata = {
  title: "Resultados",
  description: "Generated by create next app",
};

export default function Resultado() {
  return (
    <>
      <h1>Pagina resultados</h1>
    </>
  );
}
