import { Inter } from "next/font/google";
import "./globals.css";
import Navegacao from "@/components/navegacao";
import Providers from "@/Providers/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navegacao />
        {children}
      </body>
    </html>
  );
}
